### PR TITLE
3A5000-7A2000_EVB: update version to prestable202308

### PR DESCRIPTION
**Pull request by MarsDoge**
- fixes: https://github.com/loongson/Firmware/issues/34
   dmidecode -t 17 
- fixes: https://github.com/loongson/Firmware/issues/51
   Setup->Device Manager->Control Various Controllers->Iommu Setup 
- fixes: https://github.com/loongson/Firmware/issues/53
   Setup->Device Manager->Power Restore Policy Setup->Power on 
- fixes: https://github.com/loongson/Firmware/issues/55
   Setup->Select Language

### CODE REVIEW

**Comment by FanFansfan** [comment]
`[shangyatsen@loongson ~]$ dmesg | grep mmu
[    0.000000] Kernel command line: BOOT_IMAGE=/vmlinuz-6.4.1-g7bb3d7287fb4-dirty root=/dev/nvme0n1p2 rw rootflags=subvol=@ rootfstype=btrfs console=ttyS0,115200 loglevel=8 loongson_iommu=on
[    0.000000] Unknown kernel command line parameters "BOOT_IMAGE=/vmlinuz-6.4.1-g7bb3d7287fb4-dirty loongson_iommu=on", will be passed to user space.
[    0.365917] iommu: Default domain type: Translated 
[    0.365921] iommu: DMA domain TLB invalidation policy: strict mode 
[    3.495452] loongson-iommu 0000:00:1a.0: can't derive routing for PCI INT A
[    3.502372] loongson-iommu 0000:00:1a.0: PCI INT A: no GSI
[    3.507833] iommu membase (____ptrval____) pgtbase (____ptrval____) pgtsize 4000000 maxpages 1000
[   13.548840]     loongson_iommu=on
[shangyatsen@loongson ~]$ lspci
00:00.0 Host bridge: Loongson Technology LLC Hyper Transport Bridge Controller
00:00.1 Host bridge: Loongson Technology LLC Hyper Transport Bridge Controller (rev 01)
00:00.2 Host bridge: Loongson Technology LLC Device 7a20 (rev 01)
00:00.3 Host bridge: Loongson Technology LLC Device 7a30
00:03.0 Ethernet controller: Loongson Technology LLC Device 7a13
00:04.0 USB controller: Loongson Technology LLC OHCI USB Controller (rev 02)
00:04.1 USB controller: Loongson Technology LLC EHCI USB Controller (rev 02)
00:05.0 USB controller: Loongson Technology LLC OHCI USB Controller (rev 02)
00:05.1 USB controller: Loongson Technology LLC EHCI USB Controller (rev 02)
00:06.0 Multimedia video controller: Loongson Technology LLC Device 7a25 (rev 01)
00:06.1 VGA compatible controller: Loongson Technology LLC Device 7a36 (rev 02)
00:06.2 Audio device: Loongson Technology LLC Device 7a37
00:07.0 Audio device: Loongson Technology LLC HDA (High Definition Audio) Controller
00:08.0 SATA controller: Loongson Technology LLC Device 7a18
00:09.0 PCI bridge: Loongson Technology LLC Device 7a49
00:0d.0 PCI bridge: Loongson Technology LLC Device 7a49
00:0f.0 PCI bridge: Loongson Technology LLC Device 7a69
00:10.0 PCI bridge: Loongson Technology LLC Device 7a59
00:13.0 PCI bridge: Loongson Technology LLC Device 7a59
00:16.0 System peripheral: Loongson Technology LLC Device 7a1b
00:19.0 USB controller: Loongson Technology LLC Device 7a34
00:1a.0 IOMMU: Loongson Technology LLC Device 7a1f
01:00.0 Non-Volatile memory controller: SK hynix Device 2527
04:00.0 Ethernet controller: Mellanox Technologies MT27710 Family [ConnectX-4 Lx]
04:00.1 Ethernet controller: Mellanox Technologies MT27710 Family [ConnectX-4 Lx]
[root@loongson ~]# ls /sys/kernel/iommu_groups/ -ltrh
total 0
`
iommu似乎仍有问题，kernel没有适配？

**Comment by FanFansfan** [comment]
```
device linked in X4 mode GEN3
pcie phy cfg F1
wait phy status ok!
start the PCIE PHY configuration...
MIPHY apb cfg pass
complete PCIE PHY configuration !
dev 13 init begin... 
link train fail
pcie phy cfg H
wait phy status ok!
start the PCIE PHY configuration...
MIPHY apb cfg pass
complete PCIE PHY configuration !
dev 19 init begin... 
device linked in X8 mode GEN1
debug: pcie_init_time 0 ret 0x81 data 0x9027F808
debug: reset pcie ctrl 19
wait phy status ok!
start the PCIE PHY configuration...
MIPHY apb cfg pass
complete PCIE PHY configuration !
dev 19 init begin... 
device linked in X8 mode GEN1
debug: pcie_init_time 1 ret 0x81 data 0x9027F808
debug: reset pcie ctrl 19
wait phy status ok!
start the PCIE PHY configuration...
MIPHY apb cfg pass
complete PCIE PHY configuration !
dev 19 init begin... 
device linked in X8 mode GEN1
debug: pcie_init_time 2 ret 0x81 data 0x9027F808
pciShut down slave cores done!

UEFI-EDK2 loongson Initializing...
```

pcie 插入dg1的时候，启动到这里重启

**Comment by MarsDoge** [comment]
@FanFansfan 
1. 非社区版内核是存在设备节点的 /sys/kernel/iommu_groups/，不排除上游内核loongson/iommu驱动还在完善。
2. dg1 显卡插入重启与否和above4g decoding无关，重启原因为pcie和设备链路训练检测为X1导致，从log看你的设备存在多个PPB(PCI-to-PCI Bridge)初步怀疑和这个有关. 
3. dg1 显卡不能关above4g decoding，因为它请求的Mem空间较大，使用还需开启.

**Comment by FanFansfan** [comment]
> @FanFansfan
> 
>     1. 非社区版内核是存在设备节点的 /sys/kernel/iommu_groups/，不排除上游内核loongson/iommu驱动还在完善。
> 
>     2. dg1 显卡插入重启与否和above4g decoding无关，重启原因为pcie和设备链路训练检测为X1导致，从log看你的设备存在多个PPB(PCI-to-PCI Bridge)初步怀疑和这个有关.
> 
>     3. dg1 显卡不能关above4g decoding，因为它请求的Mem空间较大，使用还需开启.

对，重启跟above4g decoding无关。而且多次自动重启后有几率正常启动linux，进linux后有几率识别出显卡。

**Comment by haowuge** [comment]
这个没有RELEASE版本的有嘛，为啥这个pull那么久都没合并，是有啥bug？

**Comment by FanFansfan** [comment]
> > @FanFansfan
> > ```
> > 1. 非社区版内核是存在设备节点的 /sys/kernel/iommu_groups/，不排除上游内核loongson/iommu驱动还在完善。
> > 
> > 2. dg1 显卡插入重启与否和above4g decoding无关，重启原因为pcie和设备链路训练检测为X1导致，从log看你的设备存在多个PPB(PCI-to-PCI Bridge)初步怀疑和这个有关.
> > 
> > 3. dg1 显卡不能关above4g decoding，因为它请求的Mem空间较大，使用还需开启.
> > ```
> 
> 对，重启跟above4g decoding无关。而且多次自动重启后有几率正常启动linux，进linux后有几率识别出显卡。

发现旧版本固件协商出来的是GEN 1，这个版本也手动将插槽改成GEN 1后，不会重启。

**Pull request merged**
