### PR TITLE
Add LS2C50C2 UEFI

### PR DESCRIPTION
**Pull request by 90geek**

### CODE REVIEW

**Comment by xen0n** [comment]
Firmware file is named `*.fd.enc` instead of the default `*.fd`?

**Comment by MarsDoge** [comment]
> Firmware file is named `*.fd.enc` instead of the default `*.fd`? What's the difference?

二进制结尾添加了校验数据，在现有服务器版本UI界面下上对固件刷新时会对有效数据段进行MD5校验.

**Comment by asheplyakov** [comment]
Is it OK to flash fd.enc file directly into SPI chip?

**Comment by 90geek** [comment]
Is your current version of Loongson-UDK2018-V2.2.6? If it's this
Due to the large version span, the binary verification fails!
You can update with commands in the uefishell;
```
Shell> fs0:
FSOpen: Open '\' Success
FS0:\> spi -u UDK2018-LoongArch-LS2C50C2-V4_0_5.fd.enc
```
Or burn it up with a spi burner；

**Pull request merged**
