### PR TITLE
3A6000: Update devel for EVB_XA61200 and XA612A0 Base on Stable2402

### PR DESCRIPTION
**Pull request by MarsDoge**
Compatible with XA612A0:
If using Gnet, please open the Ethernet0 on the
Device Management -> Controller Management.

1.Optimize slow refresh issues under firmware in use 7A graphics with WUC. 
2.Support online updating of smbios by UefiShell or OsTools. 
3.Open line in with Codec.
4.Support Jm720* GPU.
5.Supports some AMD series graphics cards by default.
  REF:https://github.com/loongson/Firmware/issues/79
      https://github.com/loongson/Firmware/issues/90
      https://github.com/loongson/Firmware/issues/92
  For Nvidia, it is not supported by default, please still Switch Gpu Emu to use 7A on FW stage.
6.Add support options for switching ESP for compatibility on setup. 
7.When Adjusting and replacing the hard device, maintain the hard drive boot option. 
8.Adjusting Fan Control.
9.Add PostCode Information.
10.Update mem code v3.25.
11.Setup/Smbios optimization and some bugs fixes...

Secondary update:
1. Improve AmdgpuGop compatibility.
2. Standardized UsbBus and UsbKeyBoard.
3. Secure third-party Device Optiorom loading On Bds phase.
4. Add overclocking scheme: Advanced -> CpuAdvancedConfig 
    Note: The maximum recommendation is 2.7G 1.25V, and it can even reach 2.75G. 
    If individual adjustments result in the inability to start, please unplug the RTC battery and wait for the CMOS to fully discharge. After about 5 minutes, restart to automatically restore to the default state.

Tip: This version is intended for hobbyists and developers only.
Signed-off-by: Dongyan Qian <qiandongyan@loongson.cn>
Signed-off-by: Chao Li <lichao@loongson.cn>

### CODE REVIEW

**Comment by xen0n** [comment]
No XA612A0 files?

**Comment by xry111** [comment]
> No XA612A0 files?

The release note says you can just use it for XA612A0, but then enable Ethernet0 in Device Management -> Controller Management.

**Comment by xry111** [comment]
> 5.Supports some AMD series graphics cards by default.

It looks like the new firmware just turns off x86 emu if it fails?  I tried a boot with Resizable BAR on and x86 emu on, it boots into the OS but there's still no output during the firmware stage.

**Comment by xry111** [comment]
> > > 5.Supports some AMD series graphics cards by default.
> > 
> > 
> > It looks like the new firmware just turns off x86 emu if it fails? I tried a boot with Resizable BAR on and x86 emu on, it boots into the OS but there's still no output during the firmware stage.
> 
> Nope. x86 emu is working fine when I tried booting again and the firmware interface shows up on the DP output of the RX550. Not sure why it didn't work in the first try...

Hmm it seems depending on luck.  Sometimes there's DP output but sometimes not.

**Comment by xry111** [comment]
> > > > 5.Supports some AMD series graphics cards by default.
> > > 
> > > 
> > > It looks like the new firmware just turns off x86 emu if it fails? I tried a boot with Resizable BAR on and x86 emu on, it boots into the OS but there's still no output during the firmware stage.
> > 
> > 
> > Nope. x86 emu is working fine when I tried booting again and the firmware interface shows up on the DP output of the RX550. Not sure why it didn't work in the first try...
> 
> Hmm it seems depending on luck. Sometimes there's DP output but sometimes not.

When DP output fails there are some diagnostics:

```
AMDGPU Display Connectors
Connector 0:
  DP-10
  HPD5
  DDC: 0x4868 0x4868 0x4869 0x4869 0x486A 0x486A 0x486B 0x486B
  Encoders:
    DFP1: INTERNAL_UNIPHY1
Connector 1:
  HDMI-A-11
  HPD3
  DDC: 0x4874 0x4874 0x4875 0x4875 0x4876 0x4876 0x4877 0x4877
  Encoders:
    DFP2: INTERNAL_UNIPHY1
Connector 2:
  DVI-D-3
  HPD4
  DDC: 0x4878 0x4878 0x4879 0x4879 0x487A 0x487A 0x487B 0x487B
  Encoders:
    DFP3: INTERNAL_UNIPHY
FrameBuffer 0xE8000000000
AddrRangeMax 0xFFFFFFFF
AddrTranslationOffset 0xFFFFF20000000000
AddrLen 0x100000000
<null string>: 0x00202 AUX -> (ret=  6) FE140880h
[encoder:TMDS-0    connector:DP-10    crtc0]
unknown DP link BW code 0, using 162000
```

hope it's useful.

**Comment by xry111** [comment]
My board can build the kernel at 2600MHz/1150mV and 2700MHz/1220mV.  Below 1220mV the kernel fails to build at 2700MHz.

Trying stress-ng...

**Comment by EricGao2015** [comment]
> > > > > 5.Supports some AMD series graphics cards by default.
> > > > 
> > > > 
> > > > It looks like the new firmware just turns off x86 emu if it fails? I tried a boot with Resizable BAR on and x86 emu on, it boots into the OS but there's still no output during the firmware stage.
> > > 
> > > 
> > > Nope. x86 emu is working fine when I tried booting again and the firmware interface shows up on the DP output of the RX550. Not sure why it didn't work in the first try...
> > 
> > 
> > Hmm it seems depending on luck. Sometimes there's DP output but sometimes not.
> 
> When DP output fails there are some diagnostics:
> 
> ```
> AMDGPU Display Connectors
> Connector 0:
>   DP-10
>   HPD5
>   DDC: 0x4868 0x4868 0x4869 0x4869 0x486A 0x486A 0x486B 0x486B
>   Encoders:
>     DFP1: INTERNAL_UNIPHY1
> Connector 1:
>   HDMI-A-11
>   HPD3
>   DDC: 0x4874 0x4874 0x4875 0x4875 0x4876 0x4876 0x4877 0x4877
>   Encoders:
>     DFP2: INTERNAL_UNIPHY1
> Connector 2:
>   DVI-D-3
>   HPD4
>   DDC: 0x4878 0x4878 0x4879 0x4879 0x487A 0x487A 0x487B 0x487B
>   Encoders:
>     DFP3: INTERNAL_UNIPHY
> FrameBuffer 0xE8000000000
> AddrRangeMax 0xFFFFFFFF
> AddrTranslationOffset 0xFFFFF20000000000
> AddrLen 0x100000000
> <null string>: 0x00202 AUX -> (ret=  6) FE140880h
> [encoder:TMDS-0    connector:DP-10    crtc0]
> unknown DP link BW code 0, using 162000
> ```
> 
> hope it's useful.

`unknown DP link BW code ` this message means  the driver detected DP connector but link is not established. If the connector is in poor connection status(for example, cable is not tightly inserted), the message may show up. Can you test it serevel times and sent feedback to me? Thanks.

**Comment by xry111** [comment]
> `unknown DP link BW code ` this message means the driver detected DP connector but link is not established. If the connector is in poor connection status(for example, cable is not tightly inserted), the message may show up. Can you test it serevel times and sent feedback to me? Thanks.

It looks like (only) triggered by "save and reset" via the firmware setting interface.  In normal operation (reboot, or shutdown then boot) it does not happen at all.

**Comment by EricGao2015** [comment]
> > `unknown DP link BW code ` this message means the driver detected DP connector but link is not established. If the connector is in poor connection status(for example, cable is not tightly inserted), the message may show up. Can you test it serevel times and sent feedback to me? Thanks.
> 
> It looks like (only) triggered by "save and reset" via the firmware setting interface. In normal operation (reboot, or shutdown then boot) it does not happen at all.

Did you means `Save Changes and Reset` ?  I hava tested with RX560 and  RX580 for sereval times but it not happened.

image

**Comment by xry111** [comment]
> > > `unknown DP link BW code ` this message means the driver detected DP connector but link is not established. If the connector is in poor connection status(for example, cable is not tightly inserted), the message may show up. Can you test it serevel times and sent feedback to me? Thanks.
> > 
> > 
> > It looks like (only) triggered by "save and reset" via the firmware setting interface. In normal operation (reboot, or shutdown then boot) it does not happen at all.
> 
> Did you means `Save Changes and Reset` ? I hava tested with RX560 and RX580 for sereval times but it not happened.
> 
> image

Maybe "my own issue" then...

**Comment by FanFansfan** [comment]
内存频率手动设置为3200不生效，dmidecode显示1866MT/s

**Comment by MarsDoge** [comment]
> 内存频率手动设置为3200不生效，dmidecode显示1866MT/s

确认一下内存条是否支持3200MT？

**Comment by xen0n** [comment]
> 内存频率手动设置为3200不生效，dmidecode显示1866MT/s

可能是 non-XMP 时序只有这么高导致的

**Comment by xry111** [comment]
> > My board can build the kernel at 2600MHz/1150mV and 2700MHz/1220mV. Below 1220mV the kernel fails to build at 2700MHz.
> > Trying stress-ng...
> 
> Cannot stabilize 2700MHz even at 1260mV. OTOH 2600MHz is quite stable at the default 1150mV. I'll just stay at 2600MHz for now.
> 
> Not sure if I'll have the mood to hack the heat sink etc :).

With a large heat sink and an external fan power line (to work around #98) it runs at 2700MHz/1250mV stably.

**Comment by FanFansfan** [comment]
> > 内存频率手动设置为3200不生效，dmidecode显示1866MT/s
> 
> 确认一下内存条是否支持3200MT？

不支持，我以为这个超频是按照jedec直接设置频率，xmp能到3800的。

**Comment by lang-H** [comment]
请问更新后默认支持AMD 6000系显卡（例如RX6400）进入BIOS设置吗，还是仍旧需要先拆掉显卡关闭GPU X86模拟再使用

**Comment by EricGao2015** [comment]
> 请问更新后默认支持AMD 6000系显卡（例如RX6400）进入BIOS设置吗，还是仍旧需要先拆掉显卡关闭GPU X86模拟再使用

6000系显卡正在适配中。
但Stable 2402版已不需要拆显卡关闭x86模拟，固件中已自动屏蔽对AMD DCN显卡的x86模拟。

**Pull request merged**
