### PR TITLE
PC: Add 3A5000-7A2000 EVB V4.0.05383-beta10

### PR DESCRIPTION
**Pull request by MarsDoge**
Fixes: https://github.com/loongson/Firmware/issues/16

dbg_md5: 068b98e0ed67d4edfe0a20b114cae57f

Signed-off-by: Dongyan Qian <qiandongyan@loongson.cn>
Reviewed-by: Chao Li <lichao@loongson.cn>

### CODE REVIEW

**Comment by xry111** [comment]
I used `spi -u` to write it into the EVB (with version number 1.5 on the PCB) but it bricked.

Maybe I've done something wrong, I'll try a SPI programmer...

**Comment by xry111** [comment]
> I used `spi -u` to write it into the EVB (with version number 1.5 on the PCB) but it bricked.
> 
> Maybe I've done something wrong, I'll try a SPI programmer...

Ouch, forgot the SOP adapter when I bought the programmer.

Just purchased the adapter and it looks like I can't try it again in this week :(.

**Comment by MarsDoge** [comment]
> > I used `spi -u` to write it into the EVB (with version number 1.5 on the PCB) but it bricked.
> > Maybe I've done something wrong, I'll try a SPI programmer...
> 
> Ouch, forgot the SOP adapter when I bought the programmer.
> 
> Just purchased the adapter and it looks like I can't try it again in this week :(.

I'm guessing you may be doing something wrong, others seem to have burned it normally.

**Comment by xry111** [comment]
No luck.  Used the programmer to reprogram the flash chip but it still does not boot.

One notable symptom here is the fan on LS7A heat sink does not spin at all (hope LS7A is still alive after my several experiments w/o proper cooling :( ).

Could you provide some pointers on how to debug the issue?  Or is there the old (beta8) firmware available so I can try to revert the change?

**Comment by xry111** [comment]
FWIW: one label on my board reads "2.15.1270", and "BPLS02L02L014GB2T1292000176".  Not sure if these strings are relevant.

**Comment by MarsDoge** [comment]
> No luck. Used the programmer to reprogram the flash chip but it still does not boot.
> 
> One notable symptom here is the fan on LS7A heat sink does not spin at all (hope LS7A is still alive after my several experiments w/o proper cooling :( ).
> 
> Could you provide some pointers on how to debug the issue? Or is there the old (beta8) firmware available so I can try to revert the change?

Is it possible that the initialization of the GMem is a little slow at the first startup, have you waited for more than 5 minutes?

**Comment by xry111** [comment]
> > No luck. Used the programmer to reprogram the flash chip but it still does not boot.
> > One notable symptom here is the fan on LS7A heat sink does not spin at all (hope LS7A is still alive after my several experiments w/o proper cooling :( ).
> > Could you provide some pointers on how to debug the issue? Or is there the old (beta8) firmware available so I can try to revert the change?
> 
> Is it possible that the initialization of the GMem is a little slow at the first startup, have you waited for more than 5 minutes?

I'm afraid running 7A2000 without the fan spinning might break the hardware, so I've not tried.

Maybe I can use an "external fan"...

**Comment by MarsDoge** [comment]
> > > No luck. Used the programmer to reprogram the flash chip but it still does not boot.
> > > One notable symptom here is the fan on LS7A heat sink does not spin at all (hope LS7A is still alive after my several experiments w/o proper cooling :( ).
> > > Could you provide some pointers on how to debug the issue? Or is there the old (beta8) firmware available so I can try to revert the change?
> > 
> > 
> > Is it possible that the initialization of the GMem is a little slow at the first startup, have you waited for more than 5 minutes?
> 
> I'm afraid running 7A2000 without the fan spinning might break the hardware, so I've not tried.
> 
> Maybe I can use an "external fan"...

No need, it can withstand more than 5 minutes, you can wait a little, the fan will start working after initialization 7a.

**Comment by xry111** [comment]
> > > > No luck. Used the programmer to reprogram the flash chip but it still does not boot.
> > > > One notable symptom here is the fan on LS7A heat sink does not spin at all (hope LS7A is still alive after my several experiments w/o proper cooling :( ).
> > > > Could you provide some pointers on how to debug the issue? Or is there the old (beta8) firmware available so I can try to revert the change?
> > > 
> > > 
> > > Is it possible that the initialization of the GMem is a little slow at the first startup, have you waited for more than 5 minutes?
> > 
> > 
> > I'm afraid running 7A2000 without the fan spinning might break the hardware, so I've not tried.
> > Maybe I can use an "external fan"...
> 
> No need, it can withstand more than 5 minutes, you can wait a little, the fan will start working after initialization 7a.

Indeed, it started in 4 minutes 25 seconds.

Thanks!

**Comment by donmor** [comment]
emmm，这个为什么这么长时间都没合并啊🤔

**Comment by MarsDoge** [comment]
> emmm，这次合并时间略长啊，之前大多是一天过🤔

最近合了几个关于内置显卡VBIOS相关的配置，版本准备直接更新到Beta10

**Comment by xry111** [comment]
beta 10 打开 Above 4G Decoding 时，插在 PCIE 的 AMD RX 550 输出黑屏 (不是无输出：显示器并没有提示“无信号”，而是亮着背光但屏幕全黑)。

rel 和 debug 都存在这个问题。不确定是不是和 #1 差不多。

降级回 beta 9 后确认没有这个问题。

**Comment by MarsDoge** [comment]
> beta 10 打开 Above 4G Decoding 时，插在 PCIE 的 AMD RX 550 输出黑屏 (不是无输出：显示器并没有提示“无信号”，而是亮着背光但屏幕全黑)。
> 
> rel 和 debug 都存在这个问题。不确定是不是和 #1 差不多 (我并不确定只是无显示输出还是砖了，因为手头没有多余的 HDMI 线也没法接到 7A 的显示输出去测试)。
> 
> 降级回 beta 9 后确认没有这个问题。

 感谢 @xry111 反馈的问题很及时，方便的话再尝试下RX500，我这儿R5 230 和R7 240系列的验证是正常的. -v-

**Comment by xry111** [comment]
> > beta 10 打开 Above 4G Decoding 时，插在 PCIE 的 AMD RX 550 输出黑屏 (不是无输出：显示器并没有提示“无信号”，而是亮着背光但屏幕全黑)。
> > rel 和 debug 都存在这个问题。不确定是不是和 #1 差不多 (我并不确定只是无显示输出还是砖了，因为手头没有多余的 HDMI 线也没法接到 7A 的显示输出去测试)。
> > 降级回 beta 9 后确认没有这个问题。
> 
> 感谢 @xry111 反馈的问题很及时，方便的话再尝试下RX550，我这儿R5 230 和R7 240系列的验证是正常的. -v-

确认 RX550 也正常。

**Pull request merged**
