### PR TITLE
3A5000/3A6000_EVB: Update Prestable2405

### PR DESCRIPTION
**Pull request by MarsDoge**
main release notes:
    1.  Add YT6801UndiDxe Support.
    2.  Use 128bit to distinguish different ChipName.
    3.  UI: Add UsbXhci Controller Switch.
    5.  UI: Add SmartFan Config.
        REF: https://github.com/loongson/Firmware/issues/77
        REF: https://github.com/loongson/Firmware/issues/98
    7.  Add support for a range of chip models.
    8.  UI: Add FastBoot option.
    9.  Add SuperIo Virtual Bus.
    10.  Optimize StatusCode.
    11. Add Tpm Support.
    12. Optimize 3rd OptionRom process.
    13. UpdateFwDxe: Add inspection rules.
    14. Optimize language selection function.
    15. AcpiStrSleep: Fix cache synchronization memory.
        REF: https://github.com/loongson/Firmware/issues/88
    16. Information: Dynamically obtain cores from gEfiMpServiceProtocolGuid
    17. Update mem code to V3.35.
    18. UI: Add real-time display of temperature.
    19. Information: Display SATA DVD info in UI Setup
    20. Separate FV, decouple cache and mem execution, Lzma compresses the original logo data.
    21. Add 4M/8M flash compatibility.
    22. Add Smbios 32/64bit tables.
    23. Optimize Cpu Interface and update the Ls7a2000Ppi.efi to v1.6.2.
    24. Transfer frequency points to the kernel based on different chip models.
    25. some bug fixs.

### CODE REVIEW

**Comment by phorcys** [comment]
XA612A0 V1.1

both 0325 and this 0523 ， stuck at
```
Test CpuGetVoltage : 82 CurrentVol:1082
Test UpdateAndGetMaxFreqInfo : 401 CurrentVol:0
Test UpdateAndGetMaxFreqInfo : 417
Test UpdateAndGetMaxFreqInfo : 429
Test UpdateAndGetMaxFreqInfo : 439
Test UpdateAndGetMaxFreqInfo : 463

```
pull out cmos  battery wait 10min, still get same message.
any way to fix?

**Comment by MarsDoge** [comment]
> XA612A0 V1.1
> 
> both 0325 and this 0523 ， stuck at
> 
> ```
> Test CpuGetVoltage : 82 CurrentVol:1082
> Test UpdateAndGetMaxFreqInfo : 401 CurrentVol:0
> Test UpdateAndGetMaxFreqInfo : 417
> Test UpdateAndGetMaxFreqInfo : 429
> Test UpdateAndGetMaxFreqInfo : 439
> Test UpdateAndGetMaxFreqInfo : 463
> ```
> 
> pull out cmos battery wait 10min, still get same message. any way to fix?

In addition to unplugging the battery, make sure the host is powered off, and then wait 5 minutes to try.

**Comment by phorcys** [comment]
> > XA612A0 V1.1
> > both 0325 and this 0523 ， stuck at
> > ```
> > Test CpuGetVoltage : 82 CurrentVol:1082
> > Test UpdateAndGetMaxFreqInfo : 401 CurrentVol:0
> > Test UpdateAndGetMaxFreqInfo : 417
> > Test UpdateAndGetMaxFreqInfo : 429
> > Test UpdateAndGetMaxFreqInfo : 439
> > Test UpdateAndGetMaxFreqInfo : 463
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > pull out cmos battery wait 10min, still get same message. any way to fix?
> 
> In addition to unplugging the battery, make sure the host power cord is powered off, and then wait 5 minutes to try.
I did unplug the power cord.
ok, I'll unplug the power cord and wait 1hr .

**Comment by MarsDoge** [comment]
@phorcys XA612A0 seems that the over-Voltage design is not compatible with the XA61200. I will reply to you after confirming this. You can use https://github.com/loongson/Firmware/pull/103/commits/0d044306d4771d8a9f0cb6f140e30669b961a7ff alone.

**Comment by KatyushaScarlet** [comment]
> > XA612A0 V1.1
> > both 0325 and this 0523 ， stuck at
> > ```
> > Test CpuGetVoltage : 82 CurrentVol:1082
> > Test UpdateAndGetMaxFreqInfo : 401 CurrentVol:0
> > Test UpdateAndGetMaxFreqInfo : 417
> > Test UpdateAndGetMaxFreqInfo : 429
> > Test UpdateAndGetMaxFreqInfo : 439
> > Test UpdateAndGetMaxFreqInfo : 463
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > pull out cmos battery wait 10min, still get same message. any way to fix?
> 
> In addition to unplugging the battery, make sure the host power cord is powered off, and then wait 5 minutes to try.

Same issue here.

**Comment by MarsDoge** [comment]
@KatyushaScarlet try it https://github.com/loongson/Firmware/commit/0d044306d4771d8a9f0cb6f140e30669b961a7ff

**Comment by phorcys** [comment]
> @phorcys XA61200 seems that the over-Voltage design is not compatible with the XA612A0. I will reply to you after confirming this. You can use [0d04430](https://github.com/loongson/Firmware/commit/0d044306d4771d8a9f0cb6f140e30669b961a7ff) alone.
```

Handle 0x0000, DMI type 0, 26 bytes
BIOS Information
        Vendor: Loongson
        Version: Loongson-UDK2018-V4.0.05692-stable202402
        Release Date: 05/25/24 16:01:02
        ROM Size: 4 MB
        Characteristics:
                PCI is supported
                BIOS is upgradeable
                Boot from CD is supported
                Selectable boot is supported
                BIOS ROM is socketed
                Serial services are supported (int 14h)
                USB legacy is supported
                UEFI is supported

```

 [0d04430](https://github.com/loongson/Firmware/commit/0d044306d4771d8a9f0cb6f140e30669b961a7ff)  working well

**Comment by KatyushaScarlet** [comment]
> @KatyushaScarlet try it [0d04430](https://github.com/loongson/Firmware/commit/0d044306d4771d8a9f0cb6f140e30669b961a7ff)

It works, but still shows "202402" version.
BTW, can we expected overclocking function on XA612A0 also?

**Comment by MarsDoge** [comment]
@KatyushaScarlet  I am so sorry to reply to you only now, currently due to the difference in power supply design, we only plan to provide overclocking developer user support for the standard XA61200.

**Pull request merged**
